"""
Visualise EDA findings — generates plots saved to src/explore/plots/.

### Tradeoffs (module-level)
- Design: Save-to-file plots vs. inline notebook rendering.
- Gain: Plots are committed artifacts — reviewable in PRs, embeddable in
  markdown reports. No Jupyter dependency required.

### Scale notes
- Plotting operates on the already-profiled/aggregated data (20-200 rows),
  not the full 19K-row dataset. OOM risk: zero.
- Production equivalent: these plots would be generated by a scheduled
  reporting job (Airflow task) and pushed to an object store.
"""

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

PLOT_DIR = Path(__file__).parent / "plots"


def _ensure_plot_dir() -> Path:
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    return PLOT_DIR


def plot_ctr_distribution(df: pd.DataFrame) -> Path:
    """
    Histogram + boxplot of CTR values.

    ### Tradeoffs
    - Design: Two-panel figure (hist + boxplot) sharing the x-axis.
    - Gain: Shows both the shape (histogram) and outliers (boxplot) in one view.
  
    ### Memory
    - Operates on the ctr column only (~19K floats ≈ 150KB). No OOM risk.
    """
    ctr = df["ctr"].dropna()
    plot_dir = _ensure_plot_dir()

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 7), height_ratios=[3, 1])

    # Histogram — log-scale x to spread out the 0-100% range
    bins = np.concatenate([[-1], np.linspace(0, 100, 50), [501]])
    ax1.hist(ctr.clip(upper=500), bins=bins, color="#2196F3", edgecolor="white",
             linewidth=0.5)
    ax1.set_xlabel("CTR (%)")
    ax1.set_ylabel("Row count")
    ax1.set_title("CTR Distribution (all 19,129 rows)")
    ax1.axvline(x=100, color="red", linestyle="--", alpha=0.7, label="100% cap")
    ax1.legend()
    ax1.set_xlim(-2, 200)

    # Boxplot
    ax2.boxplot(ctr, vert=False, widths=0.5,
                boxprops=dict(color="#2196F3"),
                medianprops=dict(color="red"))
    ax2.set_xlabel("CTR (%)")
    ax2.set_xlim(-2, 200)

    fig.tight_layout()
    path = plot_dir / "ctr_distribution.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


def plot_position_bias_curve(df: pd.DataFrame) -> Path:
    """
    CTR vs. impression position bucket — the key chart that shows NO bias.

    ### Tradeoffs
    - Design: Line chart with confidence intervals vs. bar chart.
    - Gain: Line makes the flat trend visually obvious — reinforces the
      "no bias" conclusion. CI bands show where noise is high.
    """
    work = df[df["impression_pos_avg"].notna()].copy()
    work["pos_bucket"] = pd.cut(
        work["impression_pos_avg"].clip(upper=100),
        bins=list(range(0, 105, 5)),
        right=False,
    )

    agg = work.groupby("pos_bucket", observed=False).agg(
        mean_ctr=("ctr", "mean"),
        std_ctr=("ctr", "std"),
        count=("ctr", "count"),
    ).reset_index()

    # Only plot buckets with enough data
    agg = agg[agg["count"] >= 10].copy()
    agg["bucket_mid"] = agg["pos_bucket"].apply(lambda x: x.mid if hasattr(x, "mid") else 0)

    plot_dir = _ensure_plot_dir()
    fig, ax = plt.subplots(figsize=(10, 5))

    ax.plot(agg["bucket_mid"], agg["mean_ctr"], "o-", color="#2196F3",
            linewidth=2, markersize=5, label="Mean CTR per bucket")
    ax.fill_between(
        agg["bucket_mid"],
        (agg["mean_ctr"] - agg["std_ctr"]).clip(lower=0),
        agg["mean_ctr"] + agg["std_ctr"],
        alpha=0.2, color="#2196F3", label="+/- 1 std dev",
    )

    ax.set_xlabel("Impression Position (bucket midpoint)")
    ax.set_ylabel("Mean CTR (%)")
    ax.set_title("Position Bias Analysis: CTR vs. Impression Position")
    ax.legend()

    # Annotate the conclusion
    ax.annotate(
        "No position bias detected\n(R2 < 0.38 for all models)",
        xy=(0.72, 0.85), xycoords="axes fraction",
        fontsize=10, ha="left",
        bbox=dict(boxstyle="round,pad=0.5", facecolor="#FFF9C4", edgecolor="#FBC02D"),
    )

    fig.tight_layout()
    path = plot_dir / "position_bias_curve.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


def plot_candidates_per_term(df: pd.DataFrame) -> Path:
    """
    Histogram of candidates per search term.

    ### Tradeoffs
    - Design: Histogram with annotated median/mean.
    - Gain: Shows the distribution shape (long-tail right skew) and the
      100-candidate cap (p95 = p99 = 100).
    """
    term_counts = df.groupby("search_term").size()
    plot_dir = _ensure_plot_dir()

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(term_counts, bins=range(0, 110, 5), color="#4CAF50",
            edgecolor="white", linewidth=0.5)

    ax.axvline(x=term_counts.median(), color="red", linestyle="--",
               label=f"Median: {term_counts.median():.0f}")
    ax.axvline(x=term_counts.mean(), color="orange", linestyle="--",
               label=f"Mean: {term_counts.mean():.0f}")

    ax.set_xlabel("Number of candidates")
    ax.set_ylabel("Number of search terms")
    ax.set_title(f"Candidates per Search Term (n={len(term_counts)} terms)")
    ax.legend()

    fig.tight_layout()
    path = plot_dir / "candidates_per_term.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


def plot_click_sparsity(df: pd.DataFrame) -> Path:
    """
    Bar chart showing click sparsity breakdown.

    ### Tradeoffs
    - Design: Single bar chart with percentage labels.
    - Gain: Immediately communicates the 58.8% zero-click mass to
      non-technical stakeholders.
    """
    zero = (df["clicks"] == 0).sum()
    has = (df["clicks"] > 0).sum()
    plot_dir = _ensure_plot_dir()

    fig, ax = plt.subplots(figsize=(6, 5))
    bars = ax.bar(
        ["Zero clicks", "Has clicks"],
        [zero, has],
        color=["#FFCDD2", "#C8E6C9"],
        edgecolor="white",
        linewidth=2,
    )

    # Add percentage labels
    total = zero + has
    for bar, count in zip(bars, [zero, has]):
        pct = count / total * 100
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 200,
                f"{pct:.1f}%\n({count:,})",
                ha="center", va="bottom", fontsize=11, fontweight="bold")

    ax.set_ylabel("Row count")
    ax.set_title("Click Sparsity (19,129 rows)")
    ax.set_ylim(0, total * 1.15)

    fig.tight_layout()
    path = plot_dir / "click_sparsity.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


def generate_all_plots(data_dir: str = "data",
                       filename: str = "search_term_products.parquet") -> dict[str, Path]:
    """
    Generate all EDA plots and return a dict of plot name -> file path.

    ### Observability (production add-ons)
    - Timer: `with metrics.timer("visualise.duration"):`
    - Log: `logger.info("visualise", plots=len(paths))`
    """
    df = pd.read_parquet(Path(data_dir) / filename, columns=[
        "search_term", "product_id", "clicks", "impressions", "ctr",
        "impression_pos_avg",
    ])

    paths = {
        "ctr_distribution": plot_ctr_distribution(df),
        "position_bias_curve": plot_position_bias_curve(df),
        "candidates_per_term": plot_candidates_per_term(df),
        "click_sparsity": plot_click_sparsity(df),
    }

    for name, path in paths.items():
        print(f"  {name}: {path}")

    return paths


if __name__ == "__main__":
    print("[OK] Generating EDA plots...")
    paths = generate_all_plots()
    print(f"[OK] {len(paths)} plots saved to {PLOT_DIR}")
